name: publish-pypi
on:
  push:
    tags: ['v*']
jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Verify tag matches version
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          FILE_VERSION=$(python3 - <<'PY'
import sys
try:
    import tomllib
except Exception:
    import tomli as tomllib
print(tomllib.loads(open('pyproject.toml','rb').read())['tool']['poetry']['version'])
PY
)
          test "$TAG" = "$FILE_VERSION" || { echo "Tag v$TAG != pyproject $FILE_VERSION"; exit 1; }
      - run: python3 -m pip install --upgrade build
      - run: python3 -m build
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
